Repository Installomator/Installomator, pull requests merged in 2021-11, with the labels that each got.

#290 microsoft updateTool updates
  fragments/labels/microsoftcompanyportal.sh
  fragments/labels/microsoftdefenderatp.sh
  fragments/labels/microsoftedge.sh
  fragments/labels/microsoftedgeenterprisestable.sh
  fragments/labels/microsoftexcel.sh
  fragments/labels/microsoftoffice365.sh
  fragments/labels/microsoftofficebusinesspro.sh
  fragments/labels/microsoftonedrive.sh
  fragments/labels/microsoftonenote.sh
  fragments/labels/microsoftoutlook.sh
  fragments/labels/microsoftpowerpoint.sh
  fragments/labels/microsoftremotedesktop.sh
  fragments/labels/microsoftskypeforbusiness.sh
  fragments/labels/microsoftteams.sh
  fragments/labels/microsoftword.sh
  fragments/labels/microsoftyammer.sh
Labels: application, hacktoberfest

#172 Dont download pkg if we are set to silent_fail and there is blockingprocess
  Installomator.sh
Labels: enhancement

#315 CLI Installer
  CHANGELOG.md
  README.md
  fragments/functions.sh
  fragments/header.sh
  fragments/labels/adobecreativeclouddesktop.sh
  fragments/main.sh
Labels: enhancement

#316 update/installation detection
  CHANGELOG.md
  fragments/functions.sh
  fragments/main.sh
Labels: enhancement

#325 Added label for Talkdesk Callbar
  fragments/labels/talkdeskcallbar.sh
Labels: application

#322 Added label for 'nudge'
  Labels.txt
  fragments/labels/nudge.sh
Labels: application

#285 label superhuman.sh
  Labels.txt
  fragments/labels/superhuman.sh
Labels: application

#317 Theile-labels
  Labels.txt
  fragments/broken/mightymike.sh
  fragments/broken/nanosaur.sh
  fragments/labels/alephone.sh
  fragments/labels/audacity.sh
  fragments/labels/bugdom.sh
  fragments/labels/chatwork.sh
  fragments/labels/fastscripts.sh
  fragments/labels/findanyfile.sh
  fragments/labels/jabradirect.sh
  fragments/labels/jetbrainsrubymine.sh
  fragments/labels/marathon.sh
  fragments/labels/marathon2.sh
  fragments/labels/marathoninfinity.sh
  fragments/labels/mattermost.sh
  fragments/labels/mowgliiitsycal.sh
  fragments/labels/ottomatic.sh
  fragments/labels/r.sh
  fragments/labels/sequelpro.sh
  fragments/labels/smartgit.sh
Labels: application

#278 Move root user check forward and add in debug mode 2 to replicate lost functionality
  CHANGELOG.md
  fragments/arguments.sh
  fragments/functions.sh
  fragments/header.sh
  fragments/main.sh
Labels: enhancement
