Repository Installomator/Installomator, pull requests merged in 2022-09, with the labels that each got.

#653 Workspace ONE Support
  fragments/functions.sh
  fragments/header.sh
  fragments/main.sh
Labels: feature

#549 New Label: KeepingYouAwake
  fragments/labels/keepingyouawake.sh
Labels: application

#552 New Label: A Better Finder Rename 11
  fragments/labels/abetterfinderrename11.sh
Labels: application

#553 New Label: Carbon Copy Cloner
  fragments/labels/carboncopycloner.sh
Labels: application

#554 New Label: FLEXOPTIX App
  fragments/labels/flexoptixapp.sh
Labels: application

#555 New Label: Merlin Project
  fragments/labels/merlinproject.sh
Labels: application

#556 New Label: NetSpot
  fragments/labels/netspot.sh
Labels: application

#557 New Label: SynologyAssistant
  fragments/labels/synologyassistant.sh
Labels: application

#559 New Label: strongDM
  fragments/labels/strongdm.sh
Labels: application

#562 New Label: cricutdesignspace
  fragments/labels/cricutdesignspace.sh
Labels: application

#568 New label: kap
  Labels.txt
  fragments/labels/kap.sh
Labels: application

#569 New label: MASV
  fragments/labels/masv.sh
Labels: application

#570 New Label: TencentMeeting
  fragments/labels/tencentmeeting.sh
Labels: application

#575 New Label: sonicvisualiser
  fragments/labels/sonicvisualiser.sh
Labels: application

#582 New Label: Synology Drive Client
  fragments/labels/synologydriveclient.sh
Labels: application

#583 New Label: Typinator
  fragments/labels/typinator.sh
Labels: application

#584 New Label: LANCOM Advanced VPN Client
  fragments/labels/lcadvancedvpnclient.sh
Labels: application

#619 relatel label
  fragments/labels/relatel.sh
  fragments/labels/xcreds.sh
Labels: application

#672 Correct download url of libreoffice.
  fragments/functions.sh
Labels: application, bug-fix

#588 Create coconutbattery.sh
  fragments/labels/coconutbattery.sh
Labels: application

#591 New Label: Dynalist
  fragments/labels/dynalist.sh
  fragments/labels/fellow.sh
Labels: application

#665 label screamingfrogspider.sh fix, dmg per arch
  fragments/labels/screamingfrogseospider.sh
Labels: application

#598 New Label: Fujifilmwebcam
  fragments/labels/fujifilmwebcam.sh
Labels: application

#599 New Label: Fellow
  fragments/labels/fellow
Labels: application

#601 Create inetclearreportsdesigner.sh
  fragments/labels/inetclearreportsdesigner.sh
Labels: application

#607 New Label: Parallels Client
  fragments/labels/parallelsrasclient sh
Labels: application

#705 VLC version from file name
  fragments/labels/vlc.sh
Labels: application

#707 Adobe labels from isaac
  fragments/labels/adobeacrobatprodc.sh
  fragments/labels/adobecreativeclouddesktop.sh
  fragments/labels/adobereaderdc-install.sh
  fragments/labels/adobereaderdc-update.sh
Labels: application

#687 Swap Adobe URL parsing filter
  fragments/labels/adobecreativeclouddesktop.sh
Labels: application

#702 R project for Apple Silicon and intel
  fragments/labels/r.sh
  fragments/labels/rstudio.sh
Labels: application

#692 Update OBS Label
  fragments/labels/obs.sh
Labels: application

#689 New Label: Cytoscape
  fragments/labels/cytoscape.sh
Labels: application

#684 New Label: LaTeXiT
  fragments/labels/latexit.sh
Labels: application

#690 gfxCardStatus label
  fragments/labels/gfxcardstatus.sh
Labels: application

#671 New Label: Poly Lens
  fragments/labels/polylens.sh
Labels: application

#670 Created new label for Charles Proxy
  fragments/labels/charles.sh
Labels: application

#662 New Label: origin
  fragments/labels/origin.sh
Labels: application

#661 New Label: bitrix24
  fragments/labels/bitrix24.sh
Labels: application

#660 Add splashtopbusiness Label
  fragments/labels/splashtopbusiness.sh
Labels: application

#656 New Label: Zoom Outlook Plugin
  fragments/labels/zoomoutlookplugin.sh
Labels: application

#658 Dialog update when app is already at the latest version
  fragments/functions.sh
  fragments/main.sh
Labels: feature

#691 If GitHub does not give an URL we can fall back on API call
  fragments/functions.sh
Labels: feature

#701 Mdm scripts with dialog and adding to dock
  MDM/App script.sh
  MDM/App-install SS with swiftDialog and dockutil/App VFA SS github.sh
  MDM/App-install SS with swiftDialog and dockutil/App VFA SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App browser-security SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App normal SS multi-app.sh
  MDM/App-install SS with swiftDialog and dockutil/App normal SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App service SS.sh
  MDM/App-install/App VFA.sh
  MDM/App-install/App browser-security Auto-install.sh
  MDM/App-install/App browser-security SS.sh
  MDM/App-install/App normal Auto-install.sh
  MDM/App-install/App normal SS.sh
  MDM/App-install/App service Auto-install.sh
  MDM/App-loop script.sh
  MDM/App-update/App browser-security Auto-install.sh
  MDM/App-update/App normal Auto-install.sh
  MDM/InstallInstallomator.sh
  MDM/Installomator 1st Auto-install DEPNotify.sh
  MDM/Installomator 1st Auto-install.sh
  MDM/Installomator 1st SS DEPNotify.sh
  MDM/Installomator 1st SS.sh
  MDM/Installomator 1st condition.sh
  MDM/Installomator 1st prevention.sh
  MDM/Installomator update.sh
  MDM/Jamf/00_PrepareInstall_SwiftDialog.sh
  MDM/Jamf/ReadMe.md
  MDM/MDMAddigy CustomSoftware.sh
  MDM/MDMMosyle install.sh
  MDM/Manual valuesfromarguments.sh
  MDM/Progress 1st swiftDialog condition.sh
  MDM/Progress 1st swiftDialog prevention.sh
  MDM/Progress 1st swiftDialog.sh
  MDM/README.md
  MDM/Remove Installomator.sh
  MDM/install Installomator direct condition.sh
  MDM/install Installomator direct.sh
  MDM/install swiftDialog direct condition.sh
  MDM/install swiftDialog direct.sh
Labels: feature

#708 Update audacity label to check for arch
  fragments/labels/audacity.sh
Labels: application

#621 santa and nomad are forced to ignore blocking
  Installomator.sh
Labels: application, bug-fix

#634 New Label: Zotero
  fragments/labels/zotero.sh
Labels: application

#625 New Label: Archiware P5 Backup2Go
  fragments/labels/archiwareb2go.sh
Labels: application

#624 New Label: Archiware P5
  fragments/labels/archiwarepst.sh
Labels: application

#616 New Label: ChronoSync
  fragments/labels/chronosync.sh
Labels: application

#620 Add Tailscale label
  fragments/labels/tailscale.sh
Labels: application

#617 New Label: ChronoAgent
  fragments/labels/chronoagent.sh
Labels: application

#612 New Label for Zulu JDK 18
  fragments/labels/zulujdk18.sh
Labels: application

#610 New Label: Horos
  fragments/labels/horos.sh
Labels: application

#609 New Label: Filemaker Pro
  fragments/labels/filemakerpro.sh
Labels: application

#655 New Label: Egnyte Desktop Core
  fragments/labels/egnytecore.sh
Labels: application, waiting for response

#608 New Label: Java SE Development Kit 18
  fragments/labels/jdk18.sh
Labels: application
