Repository Installomator/Installomator, pull requests merged in 2022-06, with the labels that each got.

#517 Adding Workspace ONE support
  Installomator.sh
Labels: feature

#529 added function for JSON parsing using JXA
  fragments/functions.sh
  fragments/labels/firefox.sh
  fragments/labels/firefox_da.sh
  fragments/labels/firefox_intl.sh
  fragments/labels/firefoxesr.sh
  fragments/labels/firefoxesr_intl.sh
  fragments/labels/firefoxpkg.sh
  fragments/labels/firefoxpkg_intl.sh
Labels: feature

#528 html parsing now done with xmllint, should be more resilient
  fragments/labels/adobecreativeclouddesktop.sh
Labels: application

#532 New Label: Google Chrome Enterprise
  fragments/labels/googlechromeenterprise.sh
Labels: application

#535 Fixes issue with Blender not installing
  fragments/labels/blender.sh
Labels: application

#533 add appNewVersion to egnyte label
  fragments/labels/egnyte.sh
Labels: application, version-check

#540 updated assemble.sh to update Labels.txt when script is built
  utils/assemble.sh
Labels: feature

#544 Marathon Trilogy with `versionKey` added to the labels.
  fragments/labels/marathon.sh
  fragments/labels/marathon2.sh
  fragments/labels/marathoninfinity.sh
Labels: application

#560 WhatRoute label
  fragments/labels/whatroute.sh
Labels: application

#565 Barco click share
  fragments/labels/clickshare.sh
Labels: application
