Repository Installomator/Installomator, pull requests merged in 2022-05, with the labels that each got.

#434 Update functions.sh
  fragments/functions.sh
Labels: bug-fix

#448 Create displaylinkmanager.sh
  fragments/labels/displaylinkmanager.sh
Labels: application

#466 Extra logging for firefox and googlechrome labels.
  fragments/labels/firefox.sh
  fragments/labels/firefox_da.sh
  fragments/labels/firefox_intl.sh
  fragments/labels/googlechrome.sh
Labels: application

#455 Theile labels 2022 03
  MDM/App script.sh
  MDM/App-loop script.sh
  MDM/Installomator update.sh
  MDM/MDMAddigy CustomSoftware.sh
  MDM/MDMMosyle install.sh
  MDM/Manual valuesfromarguments.sh
  fragments/labels/craftmanagerforsketch.sh
  fragments/labels/dropbox.sh
  fragments/labels/duckduckgo.sh
  fragments/labels/firefox_intl.sh
  fragments/labels/firefoxesr_intl.sh
  fragments/labels/firefoxpkg_intl.sh
  fragments/labels/mightymike.sh
  fragments/labels/qgis-pr.sh
  fragments/labels/remotedesktopmanagerenterprise.sh
  fragments/labels/remotedesktopmanagerfree.sh
  fragments/labels/sketch.sh
  fragments/labels/zohoworkdrivegenie.sh
  fragments/version.sh
Labels: application

#481 Label for both Clue appliations
  fragments/labels/clue.sh
  fragments/labels/cluefull.sh
Labels: application

#479 Create MindManager Label
  fragments/labels/mindmanager.sh
Labels: application

#450 DBeaverCE
  fragments/labels/dbeaverce.sh
Labels: application

#452 Add Label for Talkdesk CX Cloud Desktop
  fragments/labels/talkdeskcxcloud.sh
Labels: application

#453 Update talkdeskcallbar label
  fragments/labels/talkdeskcallbar.sh
Labels: application

#454 Updated 'onlyofficedesktop'
  fragments/labels/onlyofficedesktop.sh
Labels: application

#463 Update 'rancherdesktop' to support arm64
  fragments/labels/rancherdesktop.sh
Labels: application

#501 Create NewLabel Flycut.sh
  fragments/labels/UltimakerCura.sh
  fragments/labels/flycut.sh
Labels: application

#503 Fix Adobe Acrobat Reader DC download & Add Unnatural Scroll Wheels
  fragments/labels/adobereaderdc-update.sh
  fragments/labels/adobereaderdc.sh
  fragments/labels/unnaturalscrollwheels.sh
Labels: application

#502 Create macoslaps.sh
  fragments/labels/macoslaps.sh
Labels: application

#499 Update Camtasia 2021
  fragments/labels/camtasia.sh
  fragments/labels/camtasia2019.sh
  fragments/labels/camtasia2020.sh
Labels: application

#497 Added support for label thunderbird_intl
  fragments/labels/thunderbird_intl.sh
Labels: application

#496 Code update and fix for firefoxesr_intl
  fragments/labels/firefoxesr_intl.sh
Labels: application

#495 Code update and fix for firefox_intl
  fragments/labels/firefox_intl.sh
Labels: application

#492 updates for ringcentral app
  fragments/labels/ringcentralapp.sh
Labels: application

#490 New Label- SonoBus
  fragments/labels/sonobus.sh
Labels: application

#484 Add latest version check for googlechromepkg
  fragments/labels/googlechromepkg.sh
Labels: application

#394 Added label propresenter7
  fragments/labels/propresenter7.sh
Labels: application

#508 Fixed Citrix Workspace appNewVersion
  fragments/labels/citrixworkspace.sh
Labels: application

#515 Update Label: Grammarly
  fragments/labels/grammarly.sh
Labels: application

#519 New App: Linear (https://linear.app/)
  fragments/labels/linear.sh
Labels: application

#522 Create filezilla.sh
  fragments/labels/filezilla.sh
Labels: application

#523 adding FontExplorer
  fragments/labels/fontexplorer.sh
Labels: application

#524 Adding hype (4)
  fragments/labels/hype.sh
Labels: application

#525 adding app imageoptim
  fragments/labels/imageoptim.sh
Labels: application

#526 Adding app Pika
  fragments/labels/pika.sh
Labels: application

#527 adding Xerox Workcentre 7800 drivers
  fragments/labels/xeroxworkcentre7800.sh
Labels: application

#507 Create new label iDrive
  fragments/labels/idrive.sh
Labels: bug, application, waiting

#509 Create new label idrivethin
  fragments/labels/idrivethin.sh
Labels: bug, application, waiting

#510 New Label: WeChat
  fragments/labels/wechat.sh
Labels: application, version-check, waiting

#512 New Label: Egnyte WebEdit
  fragments/labels/egnytewebedit.sh
Labels: application, version-check, waiting

#514 1Password 8
  Installomator.sh
  Labels.txt
  fragments/labels/1password8.sh
Labels: application, version-check, waiting
