Repository Installomator/Installomator, pull requests merged in 2022-03, with the labels that each got.

#446 Micosorft endpoint manager (intune)
  README.md
  fragments/header.sh
  fragments/main.sh
Labels: application

#431 added label for MacAdmins Python
  fragments/labels/macadminspython.sh
Labels: application

#435 Update dialog label
  fragments/labels/dialog.sh
Labels: application

#440 Fixed Microsoft Defender label
  fragments/labels/microsoftdefender.sh
Labels: application, bug-fix

#428 Update appcleaner.sh
  fragments/labels/appcleaner.sh
Labels: application

#432 added label for dockutil
  fragments/labels/dockutil.sh
Labels: application

#436 Follow git redirects
  fragments/functions.sh
Labels: bug-fix
