Repository Installomator/Installomator, pull requests merged in 2022-11, with the labels that each got.

#750 Openvpnconnectv3 fix
  fragments/labels/openvpnconnectv3.sh
Labels: application

#581 New Label: OnScreen Control
  fragments/labels/onscreencontrol.sh
Labels: bug, application, waiting for response

#618 Update tunnelblick.sh
  fragments/labels/tunnelblick.sh
Labels: invalid, application

#685 New Label: MacTeX
  fragments/labels/mactex.sh
Labels: application, version-check

#688 New Label: Projectplace
  fragments/labels/projectplace.sh
Labels: application, version-check

#710 vysor label
  fragments/labels/vysor.sh
Labels: application

#712 Create venturablocker.sh
  fragments/labels/venturablocker.sh
Labels: application

#749 Create ipvisionconnect.sh
  fragments/labels/ipvisionconnect.sh
Labels: application

#729 Create sublimemerge.sh
  fragments/labels/sublimemerge.sh
Labels: application

#728 Create subethaedit.sh
  fragments/labels/subethaedit.sh
Labels: application

#716 IBM Notifier
  fragments/labels/ibmnotifier.sh
Labels: application

#722 Create lucidlink.sh
  fragments/labels/lucidlink.sh
Labels: application

#744 Update README.md
  README.md
Labels: documentation
