Repository Installomator/Installomator, pull requests merged in 2022-12, with the labels that each got.

#713 New Label: Mendeley Reference Manager
  fragments/labels/mendeleyreferencemanager.sh
Labels: application

#714 Update/fix for macFUSE label
  fragments/labels/macfuse.sh
Labels: application

#720 bbeditpkg (new label)
  fragments/labels/bbeditpkg.sh
Labels: application

#726 further refinement to label idrive
  fragments/labels/idrive.sh
Labels: application

#727 further parsing refinement of url and version data for label idrivethin
  fragments/labels/idrivethin.sh
Labels: application

#730 Camtasia 2022 update
  fragments/labels/camtasia.sh
  fragments/labels/camtasia2021.sh
Labels: application

#731 citrixworkspace: Update parsing logic for download and version URLs
  fragments/labels/citrixworkspace.sh
Labels: application

#732 Create mist.sh
  fragments/mist.sh
Labels: application

#781 New label: boop
  Labels.txt
  fragments/labels/boop.sh
Labels: application

#785 New label ZeroTier
  fragments/labels/zerotier.sh
Labels: application

#788 Update microsoftazuredatastudio.sh
  fragments/labels/microsoftazuredatastudio.sh
Labels: bug-fix, application-issue

#789 Version check switched to CFBundleVersion
  fragments/labels/synologydriveclient.sh
Labels: bug-fix, application-issue

#778 Use Self Service icon as the 'overlayicon'
  MDM/Jamf/00_PrepareInstall_SwiftDialog.sh
  MDM/Jamf/00_Prepare_SwiftDialog.sh
Labels: improvement, sample scripts

#776 New Label: JetBrains Rider
  fragments/labels/jetbrainsrider.sh
Labels: application

#733 Create mist-cli.sh
  fragments/labels/mist-cli.sh
Labels: application

#773 New Label: Transfer
  fragments/labels/transfer.sh
Labels: application

#740 Update ultimakercura.sh
  fragments/labels/ultimakercura.sh
Labels: application

#746 Added appNewVersion variable to Prism 9 label
  fragments/labels/prism9.sh
Labels: application

#752 Create mobiletolocal.sh
  fragments/mobiletolocal.sh
Labels: application, waiting for response

#753 Create jamfcpr.sh
  fragments/labels/jamfcpr.sh
Labels: application

#754 Update nudge.sh
  fragments/labels/nudge.sh
Labels: application

#755 Create microsoftofficeremoval.sh
  fragments/labels/microsoftofficeremoval.sh
Labels: application

#760 Adding a label for VPNTracker365
  fragments/labels/vpntracker365.sh
Labels: application

#761 Update Duo Device Health label to use PKG URL
  fragments/labels/duodevicehealth.sh
Labels: application

#762 Version fix for the Skype label
  fragments/labels/skype.sh
Labels: application

#763 New Label: LG Calibration Studio
  fragments/labels/lgcalibrationstudio.sh
Labels: application

#766 updated code42 download url's with new hostname
  fragments/labels/code42.sh
Labels: application

#769 Create todoist.sh
  fragments/labels/todoist.sh
Labels: application

#770 Create netiquette.sh
  fragments/labels/netiquette.sh
Labels: application

#725 Remove "archivename" as was causing invalid dmg
  fragments/labels/drawio.sh
Labels: application, bug-fix

#759 [Update] 1Password 8 Universal pkg
  fragments/labels/1password8.sh
Labels: application
