Repository Installomator/Installomator, pull requests merged in 2022-02, with the labels that each got.

#405 fixed zulujdk13 downloadURLs
  fragments/labels/zulujdk13.sh
Labels: application, bug-fix

#268 Added option to not interrupt full screen apps like KeyNote or Zoom
  CHANGELOG.md
  fragments/functions.sh
  fragments/header.sh
  fragments/main.sh
Labels: enhancement

#373 Improved Isaac Logging
  CHANGELOG.md
  fragments/arguments.sh
  fragments/functions.sh
  fragments/header.sh
  fragments/main.sh
Labels: enhancement

#387 `versionKey` improved
  fragments/arguments.sh
  fragments/functions.sh
Labels: bug-fix

#396 Readme overhaul
  README.md
Labels: documentation

#398 Fixing if LSMinimumSystemVersion doesn't exist
  fragments/functions.sh
Labels: bug-fix

#399 Create checkInstallomator.sh
  utils/checkInstallomator.sh
Labels: enhancement

#417 Add support for the Apple Silicon version of Loom
  fragments/labels/loom.sh
Labels: application

#413 change mdfind criteria to determine location of application
  fragments/functions.sh
Labels: bug-fix
