Repository Installomator/Installomator, pull requests merged in 2022-08, with the labels that each got.

#493 Add simple, no prerequisite install script installInstallomator.sh
  MDM/InstallInstallomator.sh
Labels: feature

#473 Added BlueJeans Events by Verizon label
  Installomator.sh
  Labels.txt
Labels: application, version-check, waiting for response

#543 GitHub without API calls
  fragments/functions.sh
Labels: feature

#593 Update sublimetext.sh
  fragments/labels/sublimetext.sh
Labels: application

#537 Update talkdeskcxcloud to use JSON parsing
  fragments/labels/talkdeskcxcloud.sh
Labels: application

#536 Update talkdeskcallbar to use JSON parsing
  fragments/labels/talkdeskcallbar.sh
Labels: application

#538 Create prune.sh
  fragments/labels/prune.sh
Labels: application

#541 New label: Google Ads Editor
  googleadseditor.sh
Labels: application

#545 Add ipswupdater label using JSON parsing
  fragments/labels/ipswupdater.sh
Labels: application

#548 New Label: Duo Device Health
  fragments/labels/duodevicehealth.sh
Labels: application

#563 Update Google Drive Label
  fragments/labels/googledrive.sh
Labels: application

#585 Update Wireshark download URL
  fragments/labels/wireshark.sh
Labels: application, bug-fix

#576 Update grammarly.sh
  fragments/labels/grammarly.sh
Labels: application

#643 updated redundant exit codes
  fragments/functions.sh
  fragments/labels/macports.sh
  fragments/main.sh
Labels: bug-fix

#645 updates vmwarehorizonclient
  fragments/labels/vmwarehorizonclient.sh
Labels: application, bug-fix

#641 swiftDialog Integration
  MDM/Jamf/00_Prepare_SwiftDialog.sh
  MDM/Jamf/ReadMe.md
  MDM/Jamf/SelfServiceProgress.png
  MDM/Jamf/zz_Quit_SwiftDialog.sh
  MDM/swiftdialog_example.sh
  MDM/swiftdialog_list.sh
  fragments/arguments.sh
  fragments/functions.sh
  fragments/header.sh
  fragments/main.sh
Labels: feature
