Repository Installomator/Installomator, pull requests merged in 2023-06, with the labels that each got.

#1055 Updated Label: TeamViewerQS
  fragments/labels/teamviewerqs.sh
Labels: application, waiting for response

#1035 New Label: TeamViewer QuickSupport (custom)
  fragments/labels/teamviewerqscustom.sh
Labels: duplicate, application, waiting for response

#1054 Updated Label: TeamViewer Host
  fragments/labels/teamviewerhost.sh
Labels: application

#1053 Updated label: TeamViewer
  fragments/labels/teamviewer.sh
Labels: application

#1044 Create Label: GDevelop
  fragments/labels/gdevelop.sh
Labels: application, waiting for response

#1023 Add label: ClearTouchCollage
  fragments/labels/cleartouchcollage.sh
Labels: application

#1024 Add label: AverTouch
  fragments/labels/avertouch.sh
Labels: application

#1069 Updated Label: Cytoscape
  fragments/labels/cytoscape.sh
Labels: application

#1071 Create camtasia2023.sh
  fragments/labels/camtasia2023.sh
Labels: application, waiting for response

#1072 Add label: keeperpasswordmanager
  fragments/labels/keeperpasswordmanager.sh
Labels: application

#1073 Add label: espanso
  fragments/labels/espanso.sh
Labels: application

#1078 Label update: Everweb - version formatting fix
  fragments/labels/everweb.sh
Labels: application

#1070 label update: googledrive - add AppNewVersion
  fragments/labels/codemeter.sh
Labels: version-check

#1079 New label: CodeMeter
  fragments/labels/codemeter.sh
Labels: application

#1081 TextExpander downloadURL and appVersion updated.
  fragments/labels/textexpander.sh
Labels: application

#1083 Label update: shottr - fix versioning
  fragments/labels/shottr.sh
Labels: application
