Repository Installomator/Installomator, pull requests merged in 2023-10, with the labels that each got.

#1171 Add support for Apple Silicon builds of Azure Storage Explorer
  fragments/labels/microsoftazurestorageexplorer.sh
Labels: application

#1141 Updated Label: GraphPad Prism 9
  fragments/labels/prism9.sh
Labels: application, waiting for response

#1172 Add blocking process for Egnyte Core
  fragments/labels/egnytecore.sh
Labels: application

#1174 New Label: Elgato Stream Deck
  fragments/labels/elgatostreamdeck.sh
Labels: application

#1175 New Label: Elgato Camera Hub
  fragments/labels/elgatocamerahub.sh
Labels: application

#1178 New Label: Jetbrainsdataspell
  fragments/labels/jetbrainsdataspell.sh
  fragments/labels/jetbrainsgoland.sh
Labels: application

#1179 New Label: Digiexam
  fragments/labels/digiexam.sh
Labels: application

#1183 New Label: Acorn image editor
  fragments/labels/acorn.sh
Labels: application

#1184 New Label: Adium instant messenger
  fragments/labels/adium.sh
Labels: application

#1185 New Labels: Chemdoodle and Chemdoodle 3D
  fragments/labels/chemdoodle.sh
Labels: application

#1186 New Labels: RealVNC Server and Viewer
  fragments/labels/realvnc.sh
Labels: application

#1187 updated dialog label to new repo URL
  fragments/labels/dialog.sh
Labels: application

#1188 New Label: texshop
  fragments/labels/texshop.sh
Labels: application

#1190 New Label: franz
  fragments/labels/franz.sh
Labels: application

#1191 New Label: sequelace
  fragments/labels/sequelace.sh
Labels: application

#1197 Updated Label: MySQL Workbench CE
  fragments/labels/mysqlworkbenchce.sh
Labels: application

#1198 tunnelblick.sh to use beta
  fragments/labels/tunnelblick.sh
Labels: application

#1199 Add Label Suite
  fragments/labels/suitestudio.sh
Labels: application

#1216 Maxon changed "Mac" to "mac" in download link
  fragments/labels/magicbullet.sh
  fragments/labels/trapcode.sh
Labels: application

#1204 Create libericajdk8ltsfull.sh
  fragments/labels/libericajdk8ltsfull.sh
Labels: application

#1205 Create libericajdk11ltsfull.sh
  fragments/labels/libericajdk11ltsfull.sh
Labels: application

#1206 Create libericajdk17ltsfull.sh
  fragments/labels/libericajdk17ltsfull.sh
Labels: application

#1209 Update lcadvancedvpnclient: Adjustment of appNewVersion due to change…
  fragments/labels/lcadvancedvpnclient.sh
Labels: application

#1212 Create JamfCheck label (new app)
  fragments/labels/jamfcheck.sh
Labels: application

#1258 Clarifying log entries about app reopen and blocking process behavior…
  fragments/functions.sh
  fragments/header.sh
  fragments/main.sh
Labels: improvement

#1213 Update canva.sh
  fragments/labels/canva.sh
Labels: application

#1224 Office Reset Tools - Adding missing labels
  fragments/labels/microsoftexcelreset.sh
  fragments/labels/microsoftlicensereset.sh
  fragments/labels/microsoftonenotereset.sh
  fragments/labels/microsoftoutlookdataremoval.sh
  fragments/labels/microsoftpowerpointreset.sh
  fragments/labels/microsoftskypeforbusinessremovaltool.sh
  fragments/labels/microsoftteamsreset.sh
  fragments/labels/microsoftwordreset.sh
  fragments/labels/webextoolsremoval.sh
  fragments/labels/zoomoutlookpluginremoval.sh
Labels: application

#1226 Update zohoworkdrivetruesync.sh
  fragments/labels/zohoworkdrivetruesync.sh
Labels: application

#1227 new label plexmediaserver
  fragments/labels/plexmediaserver.sh
Labels: application

#1228 Reflector4
  fragments/labels/reflector4.sh
Labels: application

#1230 fix displaylinkmanager downloadURL & appNewVersion
  fragments/labels/displaylinkmanager.sh
Labels: application

#1234 Create snagit2024.sh
  fragments/labels/snagit.sh
  fragments/labels/snagit2023.sh
Labels: application

#1238 Label Update: virtualbox - downloadUrl and appNewVersion
  fragments/labels/virtualbox.sh
Labels: application

#1241 Update python.sh
  fragments/labels/python.sh
Labels: application

#1243 Update royaltsx.sh
  fragments/labels/royaltsx.sh
Labels: application

#1229 Improved commenting in script
  fragments/arguments.sh
  fragments/main.sh
Labels: documentation

#1246 Create label clipgrab.sh
  fragments/labels/clipgrab.sh
Labels: application

#1120 New Label: LibreOffice Language Pack (intl)
  fragments/labels/libreofficelanguagepack_intl.sh
Labels: bug, application

#1249 Create labels for Processing
  fragments/labels/processing3.sh
  fragments/labels/processing4.sh
Labels: application

#1261 Update kimplusclientmodul.sh
  fragments/labels/kimplusclientmodul.sh
Labels: application

#1250 Create isadora.sh
  fragments/labels/isadora.sh
Labels: application

#1252 New label - homebrew
  fragments/labels/homebrew.sh
  utils/2023-10-11-18-09-26/latest
Labels: application

#1254 Create Label for Dragonframe 5
  fragments/labels/dragonframe5.sh
Labels: application

#1255 Create Label for KeyShot 12
  fragments/labels/keyshot12.sh
Labels: application

#1256 Create Label for Beam Studio
  fragments/labels/beamstudio.sh
Labels: application
