Repository Installomator/Installomator, pull requests merged in 2023-08, with the labels that each got.

#1077 added bravepkg.sh
  fragments/labels/bravepkg.sh
Labels: application, waiting for response

#1087 New Label: catoclient
  fragments/labels/catoclient.sh
Labels: application

#1088 Dropbox with Apple Silicon support
  fragments/labels/dropbox.sh
Labels: application, bug-fix

#1094 moved Xcreds download back to twocanoes website
  fragments/labels/xcreds.sh
Labels: application

#1095 Updated Label: NVivo
  fragments/labels/nvivo13.sh
  fragments/labels/nvivo14.sh
Labels: application

#1097 Updated Label: boxdrive
  fragments/labels/boxdrive.sh
Labels: application

#1098 New Label: Escrow Buddy
  fragments/labels/escrowbuddy.sh
Labels: application

#1100 New Label: mdmwatchdog by Addigy
  fragments/labels/mdmwatchdog.sh
Labels: application

#1103 Create surfdrive.sh
  fragments/labels/surfdrive.sh
Labels: application

#1121 New Label: KIMplus Clientmodul
  fragments/labels/kimplusclientmodul.sh
Labels: application

#1122 New Label: starfaceuccclient
  fragments/labels/starfaceuccclient.sh
Labels: application

#1123 New Laber: starface72x
  fragments/labels/starface72x.sh
Labels: application

#1124 New Label: starface73x
  fragments/labels/starface73x.sh
Labels: application

#1131 New label: jre8
  fragments/labels/jre8.sh
Labels: application

#1134 New Label: morisawadesktopmanager
  fragments/labels/morisawadesktopmanager.sh
Labels: application

#1151 New label: VMware Fusion
  Labels.txt
  fragments/labels/vmwarefusion.sh
Labels: application

#1110 'qlab' added to labels
  fragments/labels/qlab.sh
Labels: application

#1119 Label update: libreoffice
  fragments/labels/libreoffice.sh
Labels: application

#1136 Updated Label: TeamViewer
  fragments/labels/teamviewer.sh
Labels: application

#1109 New label TeamViewer Host custom
  fragments/labels/teamviewerhostcustom.sh
Labels: application

#1138 Updated Label: TeamViewer Host
  fragments/labels/teamviewerhost.sh
Labels: application

#1139 Updated Label: TeamViewer QuickSupport (custom)
  fragments/labels/teamviewerqscustom.sh
Labels: application

#1108 Create proofpointautoupdater.sh
  fragments/labels/proofpointautoupdater.sh
Labels: application, application-issue

#1140 New Label: GraphPad Prism 10
  fragments/labels/prism10.sh
Labels: application

#1142 New Label: Adobe Digital Editions
  fragments/labels/adobedigitaleditions.sh
Labels: application

#1143 Label Vivi app
  fragments/labels/vivi.sh
Labels: application

#1146 New Label: Keystore Explorer
  fragments/labels/keystoreexplorer.sh
Labels: application

#1147 Updated Label: Inkscape
  fragments/labels/inkscape.sh
Labels: application

#1148 Update Label: Slack
  fragments/labels/slack.sh
Labels: application

#1150 New Label: Sassafras KeyAccess client for AllSight (formerly KeyServer)
  fragments/labels/sassafraskeyaccess.sh
Labels: application

#1152 Add Label: Burp Suite Professional and Community Edition
  Labels.txt
  fragments/labels/burpsuitecommunityedition.sh
  fragments/labels/burpsuiteprofessional.sh
Labels: application

#1153 New label: Print by WeWork
  fragments/labels/weprint.sh
Labels: application

#1155 Update nextcloud Label
  fragments/labels/nextcloud.sh
Labels: application

#1157 Adding FileWave as an MDM
  fragments/header.sh
  fragments/main.sh
Labels: feature, improvement

#1159 New label : Salesforce CLI
  fragments/labels/salesforcesfdx.sh
  utils/buildLabel.sh
Labels: application

#1161 Create zulip.sh
  fragments/labels/zulip.sh
Labels: application

#1166 Mailmate: Update Version Check
  fragments/labels/mailmate.sh
Labels: application

#1158 New Label: shotcut
  Labels.txt
  fragments/labels/shotcut.sh
Labels: application
