Repository Installomator/Installomator, pull requests merged in 2023-02, with the labels that each got.

#865 Adding `vonagebusiness` label
  fragments/labels/vonagebusiness.sh
Labels: application

#855 New label: Jump Desktop (jumpdesktop)
  fragments/labels/jumpdesktop.sh
Labels: application

#856 New label: MySQLWorkbench (mysqlworkbenchce)
  fragments/labels/mysqlworkbenchce.sh
Labels: application

#857 New label: SelfControl (selfcontrol)
  fragments/labels/selfcontrol.sh
Labels: application

#837 New label: Synology Active Backup for Business Agent
  fragments/labels/synologyactivebackupforbusinessagent.sh
Labels: application

#840 Add Chrome Remote Desktop
  fragments/labels/chromeremotedesktop.sh
Labels: application

#854 Update code for Google Ads Editor (googleadseditor)
  fragments/labels/googleadseditor.sh
Labels: application

#867 adobeacrobatdc: added pkgName
  fragments/labels/adobeacrobatprodc.sh
Labels: application, application-issue

#882 macports: add support for macOS Ventura
  fragments/labels/macports.sh
Labels: application, application-issue

#875 New Label: Java SE 17
  fragments/labels/jdk17.sh
Labels: application

#881 Update Alfred 5
  fragments/labels/alfred.sh
Labels: application-issue

#874 Update jdk18.sh
  fragments/labels/jdk18.sh
Labels: application-issue

#880 New Label: Java SE 19
  fragments/labels/jdk19.sh
Labels: application

#883 Update musescore.sh
  fragments/labels/musescore.sh
Labels: application-issue

#884 Update ultimakercura.sh
  fragments/labels/ultimakercura.sh
Labels: application

#885 Update microsoftoffice365.sh
  fragments/labels/microsoftoffice365.sh
Labels: application-issue

#826 Create microsoftonedrive-rollingout.sh
  fragments/labels/microsoftonedrive-rollingout.sh
Labels: application

#887 Nudge: Update Team ID
  fragments/labels/nudge.sh
  fragments/labels/nudgesuite.sh
Labels: application, application-issue

#889 drawio: Added archiveName to download the Universal build
  fragments/labels/drawio.sh
Labels: universal, application-issue

#891 New Label: Island
  fragments/labels/island.sh
Labels: application

#893 Firefoxpkg intl
  fragments/labels/firefoxpkg_intl.sh
Labels: application-issue

#894 New Label: backgroundmusic
  fragments/labels/backgroundmusic.sh
Labels: application

#895 Update 1passwordcli.sh fragment for 1Password CLI version 2
  fragments/labels/1passwordcli.sh
Labels: application-issue

#900 fixed nudgesuite downloadURL
  fragments/labels/nudgesuite.sh
Labels: application-issue

#896 new label: ClickUp
  fragments/labels/clickup.sh
Labels: application

#901 Label wrike
  fragments/labels/wrikeformac.sh
Labels: application

#904 Virtualbox: add architecture specific downloadURL
  fragments/labels/virtualbox.sh
Labels: universal, application-issue

#909 Create label for mkuser
  fragments/labels/mkuser.sh
Labels: application

#860 appClosed being set prematurely
  Installomator.sh
Labels: duplicate, improvement

#903 made Notarization check for apps more accurate
  Installomator.sh
Labels: improvement
