Repository Installomator/Installomator, pull requests merged in 2023-04, with the labels that each got.

#923 Create monitorcontrol label
  fragments/labels/monitorcontrol.sh
Labels: application

#928 Support for Kandji MDM
  MDM/App-install SS with swiftDialog and dockutil/App VFA SS github.sh
  MDM/App-install SS with swiftDialog and dockutil/App VFA SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App browser-security SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App normal SS multi-app.sh
  MDM/App-install SS with swiftDialog and dockutil/App normal SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App service SS.sh
  MDM/App-install/App VFA.sh
  MDM/App-install/App browser-security Auto-install.sh
  MDM/App-install/App browser-security SS.sh
  MDM/App-install/App normal Auto-install.sh
  MDM/App-install/App normal SS.sh
  MDM/App-install/App service Auto-install.sh
  MDM/App-update/App browser-security Auto-install.sh
  MDM/App-update/App normal Auto-install.sh
  MDM/Installomator 1st Auto-install DEPNotify.sh
  MDM/Installomator 1st Auto-install.sh
  MDM/Installomator 1st SS DEPNotify.sh
  MDM/Installomator 1st SS.sh
  MDM/Progress 1st swiftDialog.sh
  fragments/main.sh
Labels: improvement

#942 Loom label: Corrected URLs to not be CDN specific
  fragments/labels/loom.sh
Labels: application

#953 Update jabradirect.sh
  fragments/labels/jabradirect.sh
Labels: application

#972 Swiftdialog list fix
  MDM/swiftdialog_example.sh
  MDM/swiftdialog_list.sh
Labels: bug-fix

#963 Update label - Wireshark (wireshark)
  fragments/labels/wireshark.sh
Labels: application

#960 Dymoconnectdesktop label
  Installomator.sh
  Labels.txt
  fragments/labels/dymoconnectdesktop.sh
Labels: application

#961 Update label - Nessus Agent (nessusagent)
  fragments/labels/nessusagent.sh
Labels: application

#964 Update GitKraken label
  fragments/labels/gitkraken.sh
Labels: application

#966 add label crashplan
  fragments/labels/crashplan.sh
Labels: application
