Repository Installomator/Installomator, pull requests merged in 2023-05, with the labels that each got.

#926 Label update lansweeper agent options for server and agentkey can be used at the same time
  fragments/labels/lsagent.sh
Labels: application

#771 Prompt timeout
  fragments/functions.sh
  fragments/header.sh
Labels: feature

#969 Change appName for adobecreativeclouddesktop
  fragments/labels/adobecreativeclouddesktop.sh
Labels: application

#970 openvpnconnectv3: Fix appNewVersion
  fragments/labels/openvpnconnectv3.sh
Labels: application

#971 Add Meetingbar
  Labels.txt
  fragments/labels/meetingbar.sh
Labels: application

#974 New label: Atlassian Companion
  fragments/labels/atlassiancompanion.sh
Labels: application

#929 add airtable label
  fragments/labels/airtable.sh
Labels: application

#930 add brosix label
  fragments/labels/brosix.sh
Labels: application

#931 Add label CrashplanSMB
  fragments/labels/crashplansmb.sh
Labels: application

#933 Update Adobe Reader Label to be a single label, use new naming format…
  fragments/labels/adobereaderdc-install.sh
  fragments/labels/adobereaderdc-update.sh
  fragments/labels/adobereaderdc.sh
Labels: application

#932 add hubstaff label
  fragments/labels/hubstaff.sh
Labels: application

#975 New app name for Remote Desktop Manager Free
  fragments/labels/remotedesktopmanagerfree.sh
Labels: application

#934 add label zipwhip
  fragments/labels/zipwhip.sh
Labels: application

#935 add sococo label
  fragments/labels/sococo.sh
Labels: application

#937 New label: JetBrains Gateway
  fragments/labels/jetbrainsgateway.sh
Labels: application

#940 Create Label for jamovi
  fragments/labels/jamovi.sh
Labels: application

#939 Create label for jasp
  fragments/labels/jasp.sh
Labels: application

#941 Create tower.sh
  fragments/labels/tower.sh
  fragments/labels/vmwarehorizonclient.sh
  fragments/labels/vonagebusiness.sh
Labels: application

#943 Daylite Label
  fragments/labels/daylite.sh
Labels: application

#946 Update GPGSuite downloadURL
  fragments/labels/gpgsuite.sh
Labels: application

#948 Add labels for python, anaconda, and crashplan
  fragments/labels/anaconda.sh
  fragments/labels/crashplan.sh
  fragments/labels/python.sh
Labels: application

#952 Added Smartsheet label
  fragments/labels/smartsheet.sh
Labels: application

#978 Remove printlog from downloadURLFromGit function
  fragments/functions.sh
Labels: bug, bug-fix

#980 New label: Microsoft OneDrive Reset
  fragments/labels/microsoftonedrivereset.sh
Labels: application

#981 New label: Microsoft Outlook reset
  fragments/labels/microsoftoutlookreset.sh
Labels: application

#982 create label - jupyterlab
  fragments/labels/jupyterlab.sh
Labels: application

#983 create label - miniconda
  fragments/labels/miniconda.sh
Labels: application

#984 create label - backgrounds
  fragments/labels/backgrounds.sh
Labels: application

#986 Huddly Label
  fragments/labels/huddly.sh
Labels: application

#1001 New label: Affinity Designer 2
  fragments/labels/affinitydesigner2.sh
Labels: application

#1002 New label: Affinity Photo 2
  fragments/labels/affinityphoto2.sh
Labels: application

#1003 New label: Affinity Publisher 2
  fragments/labels/affinitypublisher2.sh
Labels: application

#1017 Red Canary Mac Monitor
  fragments/labels/redcanarymacmonitor.sh
Labels: application

#1026 Update alttab-label with `appNewVersion`
  fragments/labels/alttab.sh
Labels: application

#1039 Nova text editor
  fragments/labels/nova.sh
Labels: application

#985 Cricut Design Space - fix appNewVersion with new urls
  fragments/labels/cricutdesignspace.sh
Labels: application

#1031 Minor cosmetic alignment for `printlog`
  fragments/functions.sh
Labels: bug-fix

#1029 Update label: citrixworkspace (versioning fix)
  fragments/labels/citrixworkspace.sh
Labels: application

#1030 Updated Label: Inkscape
  fragments/labels/inkscape.sh
Labels: application

#1032 Update label: grandperspective - add version
  fragments/labels/grandperspective.sh
Labels: application

#1064 new label: outset
  fragments/labels/outset.sh
Labels: application

#991 Update mattermost.sh to get rid of blocking processes
  fragments/labels/mattermost.sh
Labels: application

#993 Add label for Podman Desktop
  fragments/labels/podmandesktop.sh
Labels: application

#1063 new label: munki
  fragments/labels/munki.sh
Labels: application

#999 Oracle Java SE Development Kit 20 (jdk20)
  fragments/labels/jdk20.sh
Labels: application

#1012 New Label: xbar
  Labels.txt
  fragments/labels/xbar.sh
Labels: application

#1005 New Label: Fork
  Labels.txt
  fragments/labels/fork.sh
Labels: application

#973 New label: Modern CSV
  fragments/labels/moderncsv.sh
Labels: application

#1038 Whatroute: fix appNewVersion
  fragments/labels/whatroute.sh
Labels: application

#1045 New label cinema4d
  fragments/labels/cinema4d.sh
Labels: application

#1040 Update label: coconutbattery - more precise versioning
  fragments/labels/coconutbattery.sh
Labels: application

#1043 Update label: cryptomator - intel package name
  fragments/labels/cryptomator.sh
Labels: application

#1014 Updated label: FlowJo
  fragments/labels/flowjo.sh
Labels: application

#1015 New label: Patchomator
  fragments/labels/patchomator.sh
Labels: application

#1020 Add label: Everweb
  fragments/labels/everweb.sh
Labels: application

#1021 Add label: rustdesk
  fragments/labels/rustdesk.sh
Labels: application

#1022 New Label: displaylinkmanagergraphicsconnectivity
  fragments/labels/displaylinkmanagergraphicsconnectivity.sh
Labels: application

#1025 Update shottr.sh
  fragments/labels/shottr.sh
Labels: application

#1027 Combine Itsycal/mowgliiitsycal into one
  fragments/labels/itsycal.sh
  fragments/labels/mowgliiitsycal.sh
Labels: application

#1028 Update label: iMazingProfileEditor (add appVersion)
  fragments/labels/imazingprofileeditor.sh
Labels: application

#1051 Add native Apple Silicon downloadURL for Dialpad
  fragments/labels/dialpad.sh
Labels: application

#1059 Updated Labels: Nudge and NudgeSuite
  fragments/labels/nudge.sh
  fragments/labels/nudgesuite.sh
Labels: application

#1065 New label magicbullet
  fragments/labels/magicbullet.sh
Labels: application

#1067 Update label: bitwarden - repo change (and more)
  fragments/labels/bitwarden.sh
Labels: application

#1068 Updated Label: ScaleFT - TeamID change
  fragments/labels/scaleft.sh
Labels: application

#1046 `notifier app` variable for notifications
  CHANGELOG.md
  fragments/arguments.sh
  fragments/functions.sh
  fragments/header.sh
Labels: feature
