Repository Installomator/Installomator, pull requests merged in 2023-01, with the labels that each got.

#723 Add PCoIP Client
  fragments/labels/pcoipclient.sh
Labels: bug, application

#604 Create hmavpn.sh
  fragments/labels/hmavpn.sh
Labels: application, version-check, waiting for response

#715 anydesk label update
  fragments/labels/anydesk.sh
Labels: application

#597 Pingplotter
  fragments/labels/pingplotter.sh
Labels: application, version-check, waiting for response

#796 Corrected typo in pkgName
  fragments/labels/openvpnconnectv3.sh
Labels: application-issue

#802 GIMP label update
  fragments/labels/gimp.sh
Labels: application

#803 Fix for Microsoft Teams version
  fragments/labels/microsoftteams.sh
Labels: application

#804 jabradirect: Change from packageID to versionKey
  fragments/labels/jabradirect.sh
Labels: application-issue

#805 Update teamviewer.sh
  fragments/labels/teamviewer.sh
Labels: application-issue

#815 add Camunda Modelling tool
  Labels.txt
  fragments/labels/camunda.sh
Labels: application

#813 add BetterDisplay from github
  Labels.txt
  fragments/labels/betterdisplay.sh
Labels: application

#818 Update Installomator 1st Auto-install.sh
  MDM/App-install SS with swiftDialog and dockutil/App VFA SS github.sh
  MDM/App-install SS with swiftDialog and dockutil/App VFA SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App browser-security SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App normal SS multi-app.sh
  MDM/App-install SS with swiftDialog and dockutil/App normal SS.sh
  MDM/App-install SS with swiftDialog and dockutil/App service SS.sh
  MDM/App-install/App VFA.sh
  MDM/App-install/App browser-security Auto-install.sh
  MDM/App-install/App browser-security SS.sh
  MDM/App-install/App normal Auto-install.sh
  MDM/App-install/App normal SS.sh
  MDM/App-install/App service Auto-install.sh
  MDM/App-update/App browser-security Auto-install.sh
  MDM/App-update/App normal Auto-install.sh
  MDM/Installomator 1st Auto-install.sh
  MDM/Installomator 1st SS DEPNotify.sh
  MDM/Installomator 1st SS.sh
  MDM/Progress 1st swiftDialog.sh
  MDM/install Installomator direct.sh
  MDM/install swiftDialog direct.sh
Labels: bug-fix

#821 Adding new label - Renew by Second Son Consulting
  fragments/labels/renew-noagent.sh
  fragments/labels/renew.sh
Labels: application

#819 New label: GitKraken (gitkraken)
  fragments/labels/gitkraken.sh
Labels: application

#820 New label: Beyond Compare (beyondcomparepro)
  fragments/labels/beyondcomparepro.sh
Labels: application

#823 Fix for RStudio label
  fragments/labels/rstudio.sh
Labels: application-issue

#824 Adding label connectfonts.sh
  fragments/labels/connectfonts.sh
Labels: application

#825 New label: PopSQL (popsql)
  fragments/labels/popsql.sh
Labels: application

#827 New label: Nessus Agent (nessusagent)
  fragments/labels/nessusagent.sh
Labels: application

#829 audacity - switch to universal app
  fragments/labels/audacity.sh
Labels: application-issue

#830 new label scrollreverser from github
  fragments/labels/scrollreverser.sh
Labels: application

#638 Don't relaunch a program if user chooses "not now"
  fragments/functions.sh
Labels: bug-fix

#637 Display version info of application in notification windows for prompts
  fragments/functions.sh
Labels: feature

#833 Use swiftDialog for notifications (if installed)
  fragments/functions.sh
Labels: feature

#809 new label: Druva inSync
  Labels.txt
  fragments/labels/druvainsync.sh
Labels: application

#816 new label: Jamf Aftermath
  fragments/labels/aftermath.sh
Labels: application

#838 Create firefoxdeveloperedition.sh
  fragments/labels/firefoxdeveloperedition.sh
Labels: application

#841 Fix 1password8, add missing packageID
  fragments/labels/1password8.sh
Labels: application-issue

#842 Add Yubico Authenticator
  fragments/labels/yubicoauthenticator.sh
Labels: application

#847 Fix Loom download URL
  fragments/labels/loom.sh
Labels: application-issue

#848 New label: NodeJS (nodejs)
  fragments/labels/nodejs.sh
Labels: application

#849 Update Label Tencentmeeting to fix download URL
  fragments/labels/tencentmeeting.sh
Labels: application, application-issue

#851 new label pgadmin4
  fragments/labels/pgadmin4.sh
Labels: application

#852 resubmit #846 - branch closed by accident
  fragments/labels/openvpnconnectv3.sh
Labels: application, application-issue

#834 Argument reordering
  fragments/arguments.sh
  fragments/main.sh
Labels: argument-refactor, improvement

#808 continue running the script even if management action hangs
  fragments/functions.sh
Labels: bug-fix

#603 Only prompt once on prompt_user_then_kill
  fragments/functions.sh
Labels: feature

#844 Version check to filter by PackageID
  fragments/functions.sh
Labels: improvement
