Repository Installomator/Installomator, pull requests merged in 2024-03, with the labels that each got.

#1264 Create Label for Geneious Prime
  fragments/labels/evernote.sh
Labels: application

#1272 update evernote version
  fragments/labels/evernote.sh
Labels: application

#1275 Create nomachine.sh
  fragments/labels/nomachine.sh
Labels: application

#1276 Update mactracker label
  fragments/labels/mactracker.sh
Labels: application-issue

#1280 Typeface.app label
  fragments/labels/typeface.sh
Labels: application

#1282 new label for Jitsi Meet.app
  fragments/labels/jitsimeet.sh
Labels: application

#1283 Update protonvpn.sh
  fragments/labels/protonvpn.sh
Labels: help wanted, application

#1284 New App - Raycast
  fragments/labels/raycast.sh
Labels: application

#1285 Update jamfmigrator.sh
  fragments/labels/jamfmigrator.sh
Labels: application

#1347 Fixed: fix vlc label #1287
  fragments/labels/vlc.sh
Labels: application

#1293 Update splashtopbusiness.sh
  fragments/labels/splashtopbusiness.sh
Labels: application

#1308 Update clickshare.sh
  fragments/labels/clickshare.sh
Labels: application

#1309 Create new label for onyx
  fragments/labels/onyx.sh
Labels: application

#1310 Add label for Duet Display
  fragments/labels/duet.sh
Labels: application

#1321 Add gather / gathertown label
  fragments/labels/gather.sh
Labels: application

#1322 Add Hoppscotch Label
  fragments/labels/hoppscotch.sh
Labels: application

#1327 add CrystalFetch label
  fragments/labels/crystalfetch.sh
Labels: application

#1329 Create namiral.sh
  fragments/labels/namiral.sh
Labels: application

#1343 FIXED: Blender error -ERROR : blender : need to provide 'downloadURL' #1342
  fragments/labels/blender.sh
Labels: application

#1348 Updated Skype label
  fragments/labels/skype.sh
Labels: application

#1353 Create i1Profiler.sh
  fragments/labels/i1Profiler.sh
Labels: application

#1355 Create iriunwebcam.sh
  fragments/labels/iriunwebcam.sh
Labels: application

#1356 Update whatsapp.sh
  fragments/labels/whatsapp.sh
Labels: application

#1357 virtualbox has no ARM version
  fragments/labels/virtualbox.sh
Labels: application

#1358 Update suspiciouspackage.sh (#1350)
  fragments/labels/suspiciouspackage.sh
Labels: application

#1359 Fix Island label appNewVersion string
  fragments/labels/island.sh
Labels: application

#1360 Create microsoftadseditor.sh
  fragments/labels/dedoose.sh
Labels: application, waiting for response

#1361 Add Dedoose
  fragments/labels/dedoose.sh
Labels: application

#1362 Add new label for SAP Power Monitor.app
  fragments/labels/powermonitor.sh
Labels: application

#1369 Update WhatsApp label
  fragments/labels/whatsapp.sh
Labels: application

#1370 Reworking Wireshark label to pull from platform specific Sparkle feed
  fragments/labels/wireshark.sh
Labels: application

#1372 Adding new Label for DeepL
  fragments/labels/deepl.sh
Labels: application

#1373 Update 1password8.sh
  fragments/labels/1password8.sh
Labels: application

#1375 Update scaleft.sh
  fragments/labels/scaleft.sh
Labels: application

#1376 added appNewVersion and blockingProcesses.
  fragments/labels/webex.sh
Labels: application

#1377 Create lightburn.sh
  fragments/labels/lightburn.sh
Labels: application

#1378 Added finaldraft12, finaldraft11, evercast
  fragments/labels/evercast.sh
  fragments/labels/finaldraft11.sh
  fragments/labels/finaldraft12.sh
Labels: application

#1379 Create airtamepkg.sh
  fragments/labels/airtamepkg.sh
Labels: application

#1384 Create mobirise.sh
  fragments/labels/mobirise.sh
Labels: application

#1385 Update ultimakercura.sh
  fragments/labels/ultimakercura.sh
Labels: application

#1386 Filezilla: filename fix and ARM vs x86
  fragments/labels/filezilla.sh
Labels: application

#1387 Added a label for FontBase
  fragments/labels/fontbase.sh
Labels: application

#1432 Update maxonapp.sh
  fragments/labels/maxonapp.sh
Labels: application

#1391 Create buttercup.sh
  fragments/labels/buttercup.sh
Labels: application

#1392 ChemDoodle: Add ARM version
  fragments/labels/chemdoodle.sh
Labels: application

#1395 BeyondComparePro: Fix URL
  fragments/labels/beyondcomparepro.sh
Labels: application

#1397 Fix cinema4d label
  fragments/labels/cinema4d.sh
Labels: application

#1398 Fix postman label
  fragments/labels/postman.sh
Labels: application

#1399 keeperpasswordmanager: Add appNewVersion
  fragments/labels/keeperpasswordmanager.sh
Labels: application

#1400 sketch label: fix appNewVersion
  fragments/labels/sketch.sh
Labels: application

#1401 Smartsheet: Add appNewVersion
  fragments/labels/smartsheet.sh
Labels: application

#1402 tableaudesktop: Add appNewVersion
  fragments/labels/tableaudesktop.sh
Labels: application

#1403 New label: NWEA Secure Testing Browser
  fragments/labels/nweasecuretestingbrowser.sh
Labels: application

#1404 JetBrains labels: Fix appNewVersion
  fragments/labels/jetbrainsclion.sh
  fragments/labels/jetbrainsdatagrip.sh
  fragments/labels/jetbrainsdataspell.sh
  fragments/labels/jetbrainsgateway.sh
  fragments/labels/jetbrainsgoland.sh
  fragments/labels/jetbrainsintellijidea.sh
  fragments/labels/jetbrainsintellijideace.sh
  fragments/labels/jetbrainsphpstorm.sh
  fragments/labels/jetbrainspycharm.sh
  fragments/labels/jetbrainspycharmce.sh
  fragments/labels/jetbrainsrider.sh
  fragments/labels/jetbrainsrubymine.sh
  fragments/labels/jetbrainstoolbox.sh
  fragments/labels/jetbrainswebstorm.sh
Labels: application

#1406 Create symhelper.sh label
  fragments/labels/symhelper.sh
Labels: application

#1408 Create anastasiysextensionmanager.sh
  fragments/labels/anastasiysextensionmanager.sh
Labels: application

#1297 new label: yubikeymanager
  fragments/labels/yubikeymanager.sh
Labels: application

#1300 Create new label for AutoMounter from Pixeleyes
  fragments/labels/automounter.sh
Labels: application

#1301 Create New Label for Apache Directory Studio
  fragments/labels/apachedirectorystudio.sh
Labels: application

#1424 Create logitune.sh
  fragments/labels/logitune.sh
Labels: application

#1436 Update pritunl.sh
  fragments/labels/pritunl.sh
Labels: application

#1419 Update horos.sh
  fragments/labels/horos.sh
Labels: application

#1438 Update nvivo14.sh
  fragments/labels/nvivo14.sh
Labels: application

#1439 New Label: Azul Zulu JDK 21
  fragments/labels/zulujdk21.sh
Labels: application

#1450 Update bravepkg.sh
  fragments/labels/bravepkg.sh
Labels: application

#1544 added '--no-rcs' to shebang to avoid escalation attempts using '$HOME/.zshenv'
  Installomator.sh
  MDM/Jamf/00_Prepare_SwiftDialog.sh
  MDM/Jamf/zz_Quit_SwiftDialog.sh
  MDM/Remove Installomator.sh
  MDM/swiftdialog_example.sh
  MDM/swiftdialog_list.sh
  fragments/header.sh
  utils/assemble.sh
  utils/buildLabel.sh
  utils/checkInstallomator.sh
  utils/checkLabels.sh
  utils/extractLabels.sh
  utils/test-pr.sh
Labels: bug, bug-fix

#1458 Create raindropio.sh
  fragments/labels/raindropio.sh
Labels: application

#1302 Create new label for NordVPN
  fragments/labels/nordvpn.sh
Labels: application

#1306 new label: stats
  fragments/labels/stats.sh
Labels: application

#1312 Add Groove OmniDialer label
  fragments/labels/grooveomnidialerenterpriseedition.sh
Labels: application, waiting for response

#1323 Update Duo Device Health to Duo Desktop
  fragments/labels/duodesktop.sh
  fragments/labels/duodevicehealth.sh
Labels: application

#1344 FIXED: OBS file name format changed #1335
  fragments/labels/obs.sh
Labels: application, waiting for response

#1429 New label: Node.js LTS Version
  fragments/labels/nodejslts.sh
Labels: application, waiting for response

#1435 Update universe.sh
  fragments/labels/universe.sh
Labels: application

#1441 New Label: Eclipse Temurin 8
  fragments/labels/eclipsetemurin8.sh
Labels: application

#1442 New Label: Eclipse Temurin 17
  fragments/labels/eclipsetemurin17.sh
Labels: application

#1443 New Label: Eclipse Temurin 11
  fragments/labels/eclipsetemurin11.sh
Labels: application

#1444 New Label: Eclipse Temurin 21
  fragments/labels/eclipsetemurin21.sh
Labels: application

#1393 Vagrant: Add ARM Version
  fragments/labels/vagrant.sh
Labels: application

#1468 EPOS Connect
  fragments/labels/eposconnect.sh
Labels: application

#1470 Youlean Loudness Meter 2 label
  fragments/labels/youleanloudnessmeter.sh
Labels: application

#1471 Soundly
  fragments/labels/soundly-placeit.sh
  fragments/labels/soundly.sh
Labels: application
