Repository Installomator/Installomator, pull requests merged in 2024-04, with the labels that each got.

#1333 New URL for hpeasystart label
  fragments/labels/hpeasystart.sh
Labels: application

#1475 GLPI-agent
  fragments/labels/glpiagent.sh
Labels: application

#1477 Update autodeskfusion360admininstall.sh
  fragments/labels/autodeskfusion360admininstall.sh
Labels: application

#1479 New Label: Skim
  fragments/labels/skim.sh
Labels: application

#1480 New label expressvpn
  fragments/labels/expressvpn.sh
Labels: application

#1569 Update googlechromepkg.sh
  fragments/labels/googlechromepkg.sh
Labels: application, application-issue

#1489 New Label: Freeplane
  fragments/labels/freeplane.sh
Labels: application

#1491 Create scenebuilder.sh
  fragments/labels/scenebuilder.sh
Labels: application

#1493 New Label: Apache NetBeans
  fragments/labels/apachenetbeans.sh
Labels: application

#1494 Update asana for universal app
  fragments/labels/asana.sh
Labels: application

#1498 Update miro.sh
  fragments/labels/miro.sh
Labels: application

#1488 New Label: Scribus
  fragments/labels/scribus.sh
Labels: application

#1502 New Label: Thonny
  fragments/labels/thonny.sh
Labels: application

#1503 New Label: Emacs
  fragments/labels/emacs.sh
Labels: application

#1504 New Label: Aquamacs
  fragments/labels/aquamacs.sh
Labels: application

#1508 New Label: SoapUI Open Source
  fragments/labels/soapuiopensource.sh
Labels: application

#1512 new label: workplacechat
  fragments/labels/workplace_chat.sh
Labels: application

#1514 Update mendeleyreferencemanager.sh
  fragments/labels/mendeleyreferencemanager.sh
Labels: application, application-issue

#1516 New Label: Mersive Solstice
  fragments/labels/solstice.sh
Labels: application

#1541 Update marathoninfinity.sh
  fragments/labels/marathoninfinity.sh
Labels: application

#1288 update notion label
  fragments/labels/notion.sh
Labels: application

#1517 New label: realvncondemandassist
  fragments/labels/realvnconedemandassist.sh
Labels: application

#1523 Update remotedesktopmanagerfree.sh
  fragments/labels/remotedesktopmanagerfree.sh
Labels: application

#1527 Create zulujdkfx17.sh
  fragments/labels/zulujdkfx17.sh
Labels: application

#1532 Update sync label for blockingProcess
  fragments/labels/sync.sh
Labels: application

#1533 Update clipgrab.sh
  fragments/labels/clipgrab.sh
Labels: application

#1535 Create mockoon.sh
  fragments/labels/mockoon.sh
Labels: application

#1538 fix displaylinkmanager label
  fragments/labels/displaylinkmanager.sh
Labels: application

#1539 Update marathon.sh
  fragments/labels/marathon.sh
Labels: application

#1540 Update marathon2.sh
  fragments/labels/marathon2.sh
Labels: application

#1550 Slack changed where the version is. Updated the appNewLabel variable
  fragments/labels/slack.sh
Labels: application

#1290 New Label: Bambustudio
  fragments/labels/bambustudio.sh
Labels: application

#1317 Adding new label: Baseline
  fragments/labels/baseline-nodaemon.sh
  fragments/labels/baseline.sh
Labels: application

#1418 Update zerotier.sh
  fragments/labels/zerotier.sh
Labels: application

#1521 Add label for Droplr
  fragments/labels/logitechoptionsplus.sh
Labels: application, waiting for response

#1531 Allow for Logitec Options Plus to fetch versions for macOS 12+
  fragments/labels/logitechoptionsplus.sh
Labels: application, waiting for response

#1546 Added appNewVersion variable
  fragments/labels/jamfconnect.sh
Labels: application

#1553 Create calibriteprofiler.sh
  fragments/labels/calibriteprofiler.sh
Labels: application

#1554 Update Download URLs for Xerox Printer Drivers
  fragments/labels/xeroxphaser7800.sh
  fragments/labels/xeroxworkcentre7800.sh
Labels: application

#1557 New Label: MacPass
  fragments/labels/macpass.sh
Labels: application

#1558 New Label: IGV
  fragments/labels/igv.sh
Labels: application

#1561 Create multipass.sh
  fragments/labels/multipass.sh
Labels: application

#1563 New Label: Hot
  fragments/labels/hot.sh
Labels: application

#1565 Update basecamp3.sh
  fragments/labels/basecamp3.sh
Labels: application

#1578 Update header.sh
  fragments/header.sh
Labels: documentation

#1572 New label : Rhino 7
  fragments/labels/rhino7.sh
Labels: application

#1573 New label : Rhino 8
  fragments/labels/rhino8.sh
Labels: application

#1579 New Label: Mountain Duck
  fragments/labels/mountainduck.sh
Labels: application

#1580 New Label: Transmit 5
  fragments/labels/transmit5.sh
Labels: application

#1570 Update zulujdk8.sh
  fragments/labels/zulujdk8.sh
Labels: application, application-issue
