Repository Installomator/Installomator, pull requests merged in 2024-08, with the labels that each got.

#1585 Update blender.sh
  fragments/labels/blender.sh
Labels: application

#1575 Update trapcode.sh - fixed appCustomVersion and appNewVersion
  fragments/labels/trapcode.sh
Labels: question, application

#1591 Update googlechromeenterprise.sh
  fragments/labels/googlechromeenterprise.sh
Labels: application

#1594 python label - added compressed to appNewVersion curl
  fragments/labels/python.sh
Labels: application-issue

#1595 Add blockingProcesses to garminexpress
  fragments/labels/garminexpress.sh
Labels: application

#1599 Fix flaky connectfonts app new version
  fragments/labels/connectfonts.sh
Labels: application

#1609 Select pgAdmin download based on architecture
  fragments/labels/pgadmin4.sh
Labels: application

#1803 Update header.sh
  fragments/header.sh
Labels: documentation
