Repository Installomator/Installomator, pull requests merged in 2024-09, with the labels that each got.

#1802 Remove talkdeskcallbar label
  fragments/labels/talkdeskcallbar.sh
Labels: application-issue

#1727 Update homebrew.sh label with new Team ID
  fragments/labels/homebrew.sh
Labels: application-issue

#1804 Update awsvpnclient.sh - Fixing appNewVersion
  fragments/labels/awsvpnclient.sh
Labels: application-issue

#1574 Create diskdrill.sh
  fragments/labels/diskdrill.sh
Labels: application, waiting for response

#1328 Create gosign.sh
  fragments/labels/gosign.sh
Labels: application

#1775 Update vscodium.sh
  fragments/labels/vscodium.sh
Labels: application

#1467 Update thunderbird_intl.sh
  fragments/labels/thunderbird_intl.sh
Labels: application

#1613 Create mailtooutlook.sh
  fragments/labels/mailtooutlook.sh
Labels: application

#1624 Update firefoxpkg_intl.sh
  fragments/labels/firefoxpkg_intl.sh
Labels: application-issue

#1627 Update eclipsetemurin17.sh
  fragments/labels/eclipsetemurin17.sh
Labels: application
