Repository Installomator/Installomator, pull requests merged in 2025-01, with the labels that each got.

#2090 New label: Jamf Printer Manager
  fragments/labels/jamfprintermanager.sh
Labels: application

#2104 Update jamfprintermanager.sh
  fragments/labels/jamfprintermanager.sh
Labels: bug-fix

#1380 Raw Therapee label
  fragments/labels/rawtherapee.sh
Labels: application

#1620 Update opera.sh
  fragments/labels/opera.sh
Labels: application

#1650 Label Fix: Snagit 2024
  fragments/labels/snagit.sh
Labels: application

#1630 Update eclipsetemurin8.sh
  fragments/labels/eclipsetemurin8.sh
Labels: application

#1629 Update eclipsetemurin11.sh
  fragments/labels/eclipsetemurin11.sh
Labels: application

#1628 Update eclipsetemurin21.sh
  fragments/labels/eclipsetemurin21.sh
Labels: application

#1637 Update autodeskfusion360admininstall.sh
  fragments/labels/autodeskfusion360admininstall.sh
Labels: application

#1639 Update sassafraskeyaccess.sh
  fragments/labels/sassafraskeyaccess.sh
Labels: application

#1641 Update processing4.sh
  fragments/labels/processing4.sh
Labels: application

#1668 Updated carboncopycloner download URL
  fragments/labels/carboncopycloner.sh
Labels: application

#1698 Update sketchupviewer downloadURL
  fragments/labels/sketchupviewer.sh
Labels: application

#1725 Updated Label for NetNewsWire
  fragments/labels/netnewswire.sh
Labels: application

#1736 update-cmake
  fragments/labels/cmake.sh
Labels: application

#1739 update-apachenetbeans
  fragments/labels/apachenetbeans.sh
Labels: application

#1752 Update surfdrive.sh
  fragments/labels/surfdrive.sh
Labels: application

#1761 Camunda: Update label for arm64/x64
  fragments/labels/camunda.sh
Labels: application

#1657 Update cryptomator.sh
  fragments/labels/cryptomator.sh
Labels: application

#1778 Update cloudflarewarp.sh
  fragments/labels/cloudflarewarp.sh
Labels: application

#1842 Update crashplan.sh to remove unnecessary blockingProcesses variable
  fragments/labels/crashplan.sh
Labels: application

#1767 Update dymoconnectdesktop.sh
  fragments/labels/dymoconnectdesktop.sh
Labels: application

#1772 Update kimplusclientmodul.sh
  fragments/labels/kimplusclientmodul.sh
Labels: application

#1781 Update obsbotwebcam.sh
  fragments/labels/obsbotwebcam.sh
Labels: application

#1784 Update polylens.sh
  fragments/labels/polylens.sh
Labels: application

#1703 Add Podman
  fragments/labels/podman.sh
Labels: application

#1770 New Label: podmandesktopairgap
  fragments/labels/podmandesktopairgap.sh
Labels: application

#1776 Created label polleverywhere
  fragments/labels/polleverywhere.sh
Labels: application

#1782 Create teladocproviderinstaller.sh
  fragments/labels/teladocproviderinstaller.sh
Labels: application

#1785 New label: Safe Exam Browser
  fragments/labels/safeexambrowser.sh
Labels: application

#1799 Added New Label launchcontrol
  fragments/labels/launchcontrol.sh
Labels: application

#1607 Added separate labels for C4D 2023 and 2024
  fragments/labels/cinema4d2023.sh
  fragments/labels/cinema4d2024.sh
Labels: application

#1610 New Label - sqlitebrowser
  fragments/labels/sqlitebrowser.sh
Labels: application

#1611 Create eul.sh
  fragments/labels/eul.sh
Labels: application

#1612 Create joplin.sh
  fragments/labels/joplin.sh
Labels: application

#1614 New Label - Vimcal
  fragments/labels/vimcal.sh
Labels: application

#2071 Add Cinema 4D 2025
  fragments/labels/cinema4d2025.sh
Labels: application

#1948 Add the Chrome user agent when fetching initial Citrix page
  fragments/labels/citrixworkspace.sh
Labels: application-issue

#2057 Update citrixworkspace.sh appNewVersion
  fragments/labels/citrixworkspace.sh
Labels: application-issue

#2152 MDM scripts reorganizing
  MDM/Jamf/ReadMe.md
  MDM/MDMs with local installed Installomator/App-install SS with swiftDialog and dockutil/App VFA SS github.sh
  MDM/MDMs with local installed Installomator/App-install SS with swiftDialog and dockutil/App VFA SS.sh
  MDM/MDMs with local installed Installomator/App-install SS with swiftDialog and dockutil/App browser-security SS.sh
  MDM/MDMs with local installed Installomator/App-install SS with swiftDialog and dockutil/App normal SS multi-app.sh
  MDM/MDMs with local installed Installomator/App-install SS with swiftDialog and dockutil/App normal SS.sh
  MDM/MDMs with local installed Installomator/App-install SS with swiftDialog and dockutil/App service SS.sh
  MDM/MDMs with local installed Installomator/App-install/App VFA.sh
  MDM/MDMs with local installed Installomator/App-install/App browser-security Auto-install.sh
  MDM/MDMs with local installed Installomator/App-install/App browser-security SS.sh
  MDM/MDMs with local installed Installomator/App-install/App normal Auto-install.sh
  MDM/MDMs with local installed Installomator/App-install/App normal SS.sh
  MDM/MDMs with local installed Installomator/App-install/App service Auto-install.sh
  MDM/MDMs with local installed Installomator/App-update/App browser-security Auto-install.sh
  MDM/MDMs with local installed Installomator/App-update/App normal Auto-install.sh
  MDM/MDMs with local installed Installomator/Installomator 1st Auto-install DEPNotify.sh
  MDM/MDMs with local installed Installomator/Installomator 1st Auto-install.sh
  MDM/MDMs with local installed Installomator/Installomator 1st SS DEPNotify.sh
  MDM/MDMs with local installed Installomator/Installomator 1st SS.sh
  MDM/MDMs with local installed Installomator/Installomator 1st condition.sh
  MDM/MDMs with local installed Installomator/Installomator 1st prevention.sh
  MDM/MDMs with local installed Installomator/Progress 1st swiftDialog condition.sh
  MDM/MDMs with local installed Installomator/Progress 1st swiftDialog prevention.sh
  MDM/MDMs with local installed Installomator/Progress 1st swiftDialog.sh
  MDM/MDMs with local installed Installomator/README.md
  MDM/MDMs with local installed Installomator/Remove Installomator.sh
  MDM/MDMs with local installed Installomator/install Installomator direct condition.sh
  MDM/MDMs with local installed Installomator/install Installomator direct.sh
  MDM/MDMs with local installed Installomator/install swiftDialog direct condition.sh
  MDM/MDMs with local installed Installomator/install swiftDialog direct.sh
Labels: documentation, improvement

#996 Additional download check
  fragments/main.sh
Labels: improvement

#1277 Make `xpath` quiet with `-q`
  fragments/functions.sh
Labels: feature

#1648 Arguments loading before and after labels
  CHANGELOG.md
  fragments/arguments.sh
  fragments/header.sh
  fragments/main.sh
Labels: feature

#2053 `mdfind` commands fixed
  fragments/functions.sh
Labels: bug-fix

#1649 Update camtasia2023.sh
  fragments/labels/camtasia2023.sh
Labels: application

#1693 Label camtasia 2024
  fragments/labels/camtasia2023.sh
  fragments/labels/camtasia2024.sh
Labels: application

#2137 Update rocket label to use xml feed for download and new version
  fragments/labels/rocket.sh
Labels: application

#2122 Cleanup of the zoomrooms label
  fragments/labels/zoomrooms.sh
Labels: application

#2135 Update flux label to include appNewVersion key
  fragments/labels/flux.sh
Labels: application

#2143 Update coconutbattery.sh
  fragments/labels/coconutbattery.sh
Labels: application

#2136 Update masv label to include appNewVersion key
  fragments/labels/masv.sh
Labels: application

#2138 Update wechat label to include appNewVersion key
  fragments/labels/wechat.sh
Labels: application

#2139 Update origin label to include appNewVersion key
  fragments/labels/origin.sh
Labels: application

#2123 Add appNewVersion key to jamfconnectconfiguration label
  fragments/labels/jamfconnectconfiguration.sh
Labels: application

#2124 Add appNewVersion key to Pacifist
  fragments/labels/pacifist.sh
Labels: application

#2125 Update defaultfolderx to use sparkle feed for downloadURL and appNewVersion
  fragments/labels/defaultfolderx.sh
Labels: application

#2126 Add appNewVersion to universaltypeclient
  fragments/labels/universaltypeclient.sh
Labels: application

#2128 Add appNewVersion to fsmonitor label
  fragments/labels/fsmonitor.sh
Labels: application

#2129 Update Aircall label to include appNewVersion key
  fragments/labels/aircall.sh
Labels: application

#2093 Update island.sh downloadURL
  fragments/labels/island.sh
Labels: application

#2084 Update DEPNotify download URL
  fragments/labels/depnotify.sh
Labels: application

#2083 Update NoMAD download URL
  fragments/labels/nomad.sh
Labels: application

#2155 Add jcpasswdmgr
  fragments/labels/jumpcloudpasswordmanager.sh
Labels: application, waiting for response
