Repository Installomator/Installomator, pull requests merged in 2025-02, with the labels that each got.

#2028 Update functions.sh to fix swiftDialog bug
  fragments/functions.sh
Labels: bug-fix

#2144 Better appNewVersion for 1Password8
  fragments/labels/1password8.sh
Labels: application, waiting for response

#2173 Update googlechromepkg.sh
  fragments/labels/googlechromepkg.sh
Labels: application

#2170 Update dymoconnectdesktop.sh
  fragments/labels/dymoconnectdesktop.sh
Labels: application

#2167 Convert tableaureader to XML feed and add appNewVersion key to the logic
  fragments/labels/tableaureader.sh
Labels: application

#1656 New label: Symantec VIP Access
  fragments/labels/symantecvipaccess.sh
Labels: application, validated

#1707 Create busycontacts.sh
  fragments/labels/busycontacts.sh
Labels: application, validated

#1712 Create Label: graphicconverter10
  fragments/labels/graphicconverter10.sh
Labels: application, validated

#1724 Add ChatGPT label (with appNewVersion)
  fragments/labels/chatgpt.sh
Labels: application, validated

#1807 Added Softube Central label
  fragments/labels/softubecentral.sh
Labels: application, validated

#1808 Create Korg Software Pass label
  fragments/labels/korgsoftwarepass.sh
Labels: application, validated

#1809 Create inMusic Software Center label
  fragments/labels/inmusicsoftwarecenter.sh
Labels: application, validated

#1846 Update caffeine.sh to remove unnecessary blockingProcesses variable
  fragments/labels/caffeine.sh
Labels: application, validated

#1847 Update iterm2.sh to remove unnecessary blockingProcesses variable
  fragments/labels/iterm2.sh
Labels: application, validated

#1848 Update rapidapi.sh to remove unnecessary blockingProcesses variable
  fragments/labels/rapidapi.sh
Labels: application, validated

#1875 Create Loopcloud label
  fragments/labels/loopcloud.sh
Labels: application, validated

#1876 Create Output Hub label
  fragments/labels/outputhub.sh
Labels: application, validated

#1885 Create VirtualBox label set
  fragments/labels/virtualboxbeta.sh
  fragments/labels/virtualboxlatest.sh
  fragments/labels/virtualboxstable.sh
Labels: application, validated

#1887 Create Midi Monitor label
  fragments/labels/midimonitor.sh
Labels: application, validated

#1888 Create SysEx Librarian label
  fragments/labels/sysexlibrarian.sh
Labels: application, validated

#1890 Create Mural label
  fragments/labels/mural.sh
Labels: application, validated

#1895 Create Steinberg Library Manager label
  fragments/labels/steinberglibrarymanager.sh
Labels: application, validated

#1896 Create Steinberg Media Bay label
  fragments/labels/steinbergmediabay.sh
Labels: application, validated

#1912 Update PlistEdit Pro label to include appNewVersion variable
  fragments/labels/plisteditpro.sh
Labels: application, validated

#1894 Create Steinberg Activation Manager label
  fragments/labels/steinbergactivationmanager.sh
Labels: application, validated

#1914 Update Telegram label appNewVersion check
  fragments/labels/telegram.sh
Labels: application, validated

#1917 Fix for broken app label displaylinkmanagergraphicsconnectivity
  fragments/labels/displaylinkmanagergraphicsconnectivity.sh
Labels: application, validated

#1923 Update LastPass to include appNewVersion variable
  fragments/labels/lastpass.sh
Labels: application, validated

#1927 Update Packages label to include appNewVersion variable
  fragments/labels/packages.sh
Labels: application, validated

#1928 Update Sourcetree label to use the sparkle feed
  fragments/labels/sourcetree.sh
Labels: application, validated

#1930 Update Plex Media Server to use json function
  fragments/labels/plexmediaserver.sh
Labels: application, validated

#1935 Create ollama label
  fragments/labels/ollama.sh
Labels: application, validated

#1941 Create osquery label
  fragments/labels/osquery.sh
Labels: application, validated

#1944 Create Thunderbird ESR Label
  fragments/labels/thunderbird.sh
  fragments/labels/thunderbirdesr.sh
Labels: application, validated

#1949 Update for ARM and INTEL installations
  fragments/labels/mongodbcompass.sh
Labels: application, validated

#1964 Update microsoftvisualstudiocode.sh
  fragments/labels/microsoftvisualstudiocode.sh
Labels: application, validated

#1968 Create Reaper label
  fragments/labels/reaper.sh
Labels: application, validated

#1973 Update Shottr label to correct URL detection
  fragments/labels/shottr.sh
Labels: application, validated

#1978 Add openeid
  fragments/labels/openeid.sh
Labels: application, validated

#1985 Create gotowebinar label
  fragments/labels/gotomeeting.sh
  fragments/labels/gotowebinar.sh
Labels: application, validated

#1997 Fix download URL for "microsoftcompanyportal" label
  fragments/labels/microsoftcompanyportal.sh
Labels: application, validated

#1998 Added fragment for label 4kvideodownloaderplus
  fragments/labels/4kvideodownloaderplus.sh
Labels: application, validated

#1980 Fix Icons label for type change
  fragments/labels/icons.sh
Labels: application, validated

#2024 amazoncorretto22jdk - new label
  fragments/labels/amazoncorretto22jdk.sh
Labels: application, validated

#2025 amazoncorretto23jdk - new label
  fragments/labels/amazoncorretto23jdk.sh
Labels: application, validated

#2034 Update Suspicious Package to use the plist version feed instead of the webpage scraping
  fragments/labels/suspiciouspackage.sh
Labels: application, validated

#2036 Create jamfconnectlaunchagent.sh
  fragments/labels/jamfconnectlaunchagent.sh
Labels: application, validated

#2058 New Label for Hudl Studio
  fragments/labels/HudlStudio.sh
Labels: application, validated

#2059 New label for Hudl Sportscode
  fragments/labels/HudlSportscode.sh
Labels: application, validated

#2060 New Label for Synergy Baseball
  fragments/labels/SynergyBaseball.sh
Labels: application, validated

#2061 New Label for DCP-o-matic 2
  fragments/labels/DCP-o-matic.sh
Labels: application, validated

#2062 New Label for Synergy Basketball
  fragments/labels/SynergyBasketball.sh
Labels: application, validated

#2063 New Label for Synergy Editor Basketball
  fragments/labels/SynergyEditorBasketball.sh
Labels: application, validated

#2064 New Label for Synergy Video Express
  fragments/labels/SynergyVideoExpress.sh
Labels: application, validated

#2065 New Label for A plasmid Editor (ApE)
  fragments/labels/ApE.sh
Labels: application, validated

#2069 New OneDrive labels that pull from the same feed as the OneDrive StandaloneUpdater tool
  fragments/labels/microsoftonedrivesuinsiders.sh
  fragments/labels/microsoftonedrivesuprod.sh
Labels: application, validated

#2072 Harmony SASE / Perimeter81 fix / update
  fragments/labels/harmonysase.sh
Labels: application, validated

#2073 Add Label: Okta Verify
  fragments/labels/oktaverify.sh
Labels: application, validated

#2076 Add appCustomVersion to gpgsuite
  fragments/labels/gpgsuite.sh
Labels: application, validated

#2078 anydesk.sh: Update Team ID
  fragments/labels/anydesk.sh
Labels: application, validated

#2079 acroniscyberprotectconnectagent.sh: Update Team ID
  fragments/labels/acroniscyberprotectconnectagent.sh
Labels: application, validated

#2087 Splitting 2 realvnc labels submitted in 1 label file
  fragments/labels/realvncserver.sh
  fragments/labels/realvncviewer.sh
Labels: application, validated

#2088 Splitting 2 chemdoodle labels submitted in 1 label file
  fragments/labels/chemdoodle.sh
  fragments/labels/chemdoodle3d.sh
Labels: application, validated

#2092 Add Ente Auth Label
  fragments/labels/enteauth.sh
Labels: application, validated

#2097 Ultraedit
  fragments/labels/ultraedit.sh
Labels: application, validated

#2098 Create ultracompare.sh
  fragments/labels/ultracompare.sh
Labels: application, validated

#2110 Update igv for Apple Silicon
  fragments/labels/igv.sh
Labels: application, validated

#2121 Create Label unityhub.sh
  fragments/labels/unityhub.sh
Labels: application, validated

#2140 Update and rename snapgeneviewer.sh to snapgene.sh
  fragments/labels/snapgene.sh
Labels: application, validated

#2141 Fix appNewVersion plus add CLIInstaller for Tunnelblick
  fragments/labels/tunnelblick.sh
Labels: application, validated

#2157 New label lunadisplay
  fragments/labels/lunadisplay.sh
Labels: application, validated

#2164 Update rodecentral.sh
  fragments/labels/rodecentral.sh
Labels: application, validated

#2168 New Label teamwire.sh
  fragments/labels/teamwire.sh
Labels: application, validated

#2013 zulujdk8 - update version check
  fragments/labels/zulujdk8.sh
Labels: application, validated

#2016 zulujdk21 = Updated new version check
  fragments/labels/zulujdk21.sh
Labels: application, validated

#2017 Zulujdk23 - new product
  fragments/labels/zulujdk23.sh
Labels: application, validated

#2019 Fix appNewVersion in "grandperspective" label
  fragments/labels/grandperspective.sh
Labels: application, validated

#2020 amazon corretto jdk 8
  fragments/labels/amazoncorretto8jdk.sh
Labels: application, validated

#2021 amazoncorretto17jdk - installed version check
  fragments/labels/amazoncorretto17jdk.sh
Labels: application, validated

#2022 amazoncorretto11jdk - installed version check
  fragments/labels/amazoncorretto11jdk.sh
Labels: application, validated

#2041 Update nodejs: added `-L` to curl to follow redirects after website changes
  fragments/labels/nodejs.sh
Labels: application, validated

#2048 Update codemeter.sh
  fragments/labels/codemeter.sh
Labels: application, validated

#2049 Update lcadvancedvpnclient.sh
  fragments/labels/lcadvancedvpnclient.sh
Labels: application, validated

#2050 Update flexoptixapp.sh
  fragments/labels/flexoptixapp.sh
Labels: application, validated

#2051 Update synologyassistant.sh
  fragments/labels/synologyassistant.sh
Labels: application, validated

#2015 New Label: OpenRefine
  fragments/labels/openrefine.sh
Labels: application, incomplete

#2004 Create Label starface90x.sh
  fragments/labels/starface90x.sh
Labels: application, incomplete
