Repository Installomator/Installomator, pull requests merged in 2025-06, with the labels that each got.

#2434 Fixes for Ableton labels
  fragments/labels/abletonlive12intro.sh
  fragments/labels/abletonlive12lite.sh
  fragments/labels/abletonlive12standard.sh
  fragments/labels/abletonlive12suite.sh
  fragments/labels/abletonlive12trial.sh
Labels: application-issue

#2441 Update displaylinkmanager.sh
  fragments/labels/displaylinkmanager.sh
Labels: application

#2442 Disable displaylinkmanagergraphicsconnectivity
  fragments/disabled/displaylinkmanagergraphicsconnectivity.sh
Labels: application

#2307 Fix output of 'Installomator.sh version'
  fragments/arguments.sh
Labels: bug, bug-fix

#2435 Fix LOGO_PATH for kandji and filewave
  MDM/MDMs with local installed Installomator/Progress 1st swiftDialog.sh
Labels: sample scripts

#2404 New Label Apple Pro Video Formats
  fragments/labels/appleprovideoformats.sh
Labels: application

#2382 Fix: Adding to Dock
  MDM/MDMs with local installed Installomator/App-install SS with swiftDialog and dockutil/App normal SS.sh
Labels: sample scripts

#2381 Fix: Check for dockutil
  MDM/MDMs with local installed Installomator/App-install SS with swiftDialog and dockutil/App normal SS.sh
Labels: sample scripts
