Repository Installomator/Installomator, pull requests merged in 2025-03, with the labels that each got.

#1879 Create EastWest Opus label
  fragments/labels/eastwestopus.sh
Labels: application, validated

#1960 Sawgrass print utility label
  fragments/labels/sawgrassprintutility.sh
Labels: application, validated

#1751 Fix keyshot2024 label
  fragments/labels/keyshot2024.sh
Labels: application, validated

#1979 Update googlechrome.sh
  fragments/labels/googlechrome.sh
Labels: application, validated

#1679 Update docker.sh
  fragments/labels/docker.sh
Labels: application

#1783 Create Installomatormate
  fragments/labels/installomatormate.sh
Labels: application

#2074 PyCharm blocking process
  fragments/labels/jetbrainspycharm.sh
  fragments/labels/jetbrainspycharmce.sh
Labels: application, validated

#2077 aftermath.sh: Update Team ID
  fragments/labels/aftermath.sh
Labels: application, validated

#2094 Update keybase.sh
  fragments/labels/keybase.sh
Labels: application, validated

#2006 Update monitorcontrol label with new team ID
  fragments/labels/monitorcontrol.sh
Labels: application, incomplete, validated

#2067 added airflow label
  fragments/labels/airflow.sh
Labels: application, validated

#2107 New label: githubcopilotforxcode
  fragments/labels/githubcopilotforxcode.sh
Labels: application, validated

#2145 Add LiveReplayer
  fragments/labels/livereplayer.sh
Labels: application, validated

#2178 Add topazphoto
  fragments/labels/topazphoto.sh
Labels: application, validated

#2179 Add Topaz Video AI
  fragments/labels/topazvideo.sh
Labels: application, validated

#2180 Update texshop.sh
  fragments/labels/texshop.sh
Labels: application, validated

#2181 Update citrixworkspace.sh
  fragments/labels/citrixworkspace.sh
Labels: application, validated

#2182 Update snagit.sh
  fragments/labels/snagit.sh
Labels: application, validated

#2185 Update deepl.sh
  fragments/labels/deepl.sh
Labels: application, validated

#2188 Update r.sh
  fragments/labels/r.sh
Labels: application, validated

#2183 Update Camtasia2024 label
  fragments/labels/camtasia2024.sh
Labels: application, attention-required

#2206 Add twingate
  fragments/labels/twingate.sh
Labels: application, validated

#2217 Fix thunderbird
  fragments/labels/thunderbird.sh
Labels: application, validated

#2218 New Label Deon
  fragments/labels/deon-cloud.sh
  fragments/labels/deon-onprem.sh
Labels: application, validated

#2219 New Label Northpole Security Santa
  fragments/labels/nps-santa.sh
Labels: application, validated

#2222 Update gotomeeting.sh
  fragments/labels/gotomeeting.sh
Labels: application, validated

#2226 Update remotedesktopmanagerenterprise.sh
  fragments/labels/remotedesktopmanagerenterprise.sh
Labels: application, validated

#2227 New label: cursorai
  fragments/labels/cursorai.sh
Labels: application, validated

#2230 Updated url's for label surfdrive
  fragments/labels/surfdrive.sh
Labels: application, validated

#2231 Camtasia2025 label
  fragments/labels/camtasia2024.sh
  fragments/labels/camtasia2025.sh
Labels: application, validated

#2233 Update axurerp10
  fragments/labels/axurerp10.sh
Labels: application, validated

#2234 Update cryptomator.sh
  fragments/labels/cryptomator.sh
Labels: application, validated

#2237 azuredatastudio: removed superfluous appName and blockingProcess
  fragments/labels/microsoftazuredatastudio.sh
Labels: application, validated

#2238 vonagebusiness: removed unnecessary appName and blockingProcesses
  fragments/labels/vonagebusiness.sh
Labels: application, validated

#2239 Update basecamp3
  fragments/labels/basecamp3.sh
Labels: application, validated

#2243 Update duodesktop
  fragments/labels/duodesktop.sh
Labels: application, validated

#2244 Update Evernote
  fragments/labels/evernote.sh
Labels: application, validated

#2245 Update garminexpress
  fragments/labels/garminexpress.sh
Labels: application, validated

#2216 Add label: redgiant
  fragments/labels/redgiant.sh
Labels: application, validated

#2220 Add appNewVersion to cloudflarewarp
  fragments/labels/cloudflarewarp.sh
Labels: application, validated

#2242 Update crashplan
  fragments/labels/crashplan.sh
Labels: application, validated

#2250 Update mmhmm
  fragments/labels/mmhmm.sh
Labels: application, validated

#2252 Update mmhmm-studio
  fragments/labels/mmhmm-studio.sh
Labels: application, validated

#2253 Update namiral
  fragments/labels/namiral.sh
Labels: application, validated

#2255 Create sqldeveloper.sh
  fragments/labels/sqldeveloper.sh
Labels: application, validated

#2258 Add kDrive
  fragments/labels/kdrive.sh
Labels: application, validated

#2259 Update bitrix24.sh
  fragments/labels/bitrix24.sh
Labels: application, validated

#2261 Update iriunwebcam
  fragments/labels/iriunwebcam.sh
Labels: application, validated

#2262 Update keepingyouawake
  fragments/labels/keepingyouawake.sh
Labels: application, validated

#2265 More reliable appNewVersion and downloadURL
  fragments/labels/topazgigapixel.sh
Labels: application, validated

#2271 Update orion
  fragments/labels/orion.sh
Labels: application, validated

#2272 Update ringcentralapp
  fragments/labels/ringcentralapp.sh
Labels: application, validated

#2273 Update ringcentralclassicapp
  fragments/labels/ringcentralclassicapp.sh
Labels: application, validated

#2274 Update sqlpropostgres
  fragments/labels/sqlpropostgres.sh
Labels: application, validated

#2275 Update sqlprostudio
  fragments/labels/sqlprostudio.sh
Labels: application, validated

#2276 Update vpntracker365
  fragments/labels/vpntracker365.sh
Labels: application, validated

#2229 Add Owncloud client
  fragments/labels/owncloud.sh
Labels: application, validated

#2257 Update theunarchiver
  fragments/labels/theunarchiver.sh
Labels: application, validated, attention-required

#2240 Fixes Fellow version
  fragments/labels/fellow.sh
Labels: application
